/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ivrix_hspell_LibHSpellJ */

#ifndef _Included_org_ivrix_hspell_LibHSpellJ
#define _Included_org_ivrix_hspell_LibHSpellJ
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ivrix_hspell_LibHSpellJ_HSPELL_OPT_DEFAULT
#define org_ivrix_hspell_LibHSpellJ_HSPELL_OPT_DEFAULT 0L
#undef org_ivrix_hspell_LibHSpellJ_HSPELL_OPT_HE_SHEELA
#define org_ivrix_hspell_LibHSpellJ_HSPELL_OPT_HE_SHEELA 1L
#undef org_ivrix_hspell_LibHSpellJ_HSPELL_OPT_LINGUISTICS
#define org_ivrix_hspell_LibHSpellJ_HSPELL_OPT_LINGUISTICS 2L
/*
 * Class:     org_ivrix_hspell_LibHSpellJ
 * Method:    hspell_init
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_org_ivrix_hspell_LibHSpellJ_hspell_1init
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     org_ivrix_hspell_LibHSpellJ
 * Method:    hspell_check_word
 * Signature: (JLjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_org_ivrix_hspell_LibHSpellJ_hspell_1check_1word
  (JNIEnv *, jclass, jlong, jstring, jintArray);

/*
 * Class:     org_ivrix_hspell_LibHSpellJ
 * Method:    hspell_trycorrect
 * Signature: (JLjava/lang/String;[[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ivrix_hspell_LibHSpellJ_hspell_1trycorrect
  (JNIEnv *, jclass, jlong, jstring, jobjectArray);

/*
 * Class:     org_ivrix_hspell_LibHSpellJ
 * Method:    hspell_is_canonic_gimatria
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ivrix_hspell_LibHSpellJ_hspell_1is_1canonic_1gimatria
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_ivrix_hspell_LibHSpellJ
 * Method:    hspell_uninit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ivrix_hspell_LibHSpellJ_hspell_1uninit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ivrix_hspell_LibHSpellJ
 * Method:    hspell_get_dictionary_path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ivrix_hspell_LibHSpellJ_hspell_1get_1dictionary_1path
  (JNIEnv *, jclass);

/*
 * Class:     org_ivrix_hspell_LibHSpellJ
 * Method:    hspell_set_dictionary_path
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ivrix_hspell_LibHSpellJ_hspell_1set_1dictionary_1path
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_ivrix_hspell_LibHSpellJ
 * Method:    hspell_enum_splits
 * Signature: (JLjava/lang/String;Lorg/ivrix/hspell/LibHSpellJ/hspell_word_split_callback_func;)I
 */
JNIEXPORT jint JNICALL Java_org_ivrix_hspell_LibHSpellJ_hspell_1enum_1splits
  (JNIEnv *, jclass, jlong, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
